// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFAufB5A1JLOiWUYy6GoGJ84isgVFzFdk',
    appId: '1:671469241941:web:9aaeffd363b70558d3f6dc',
    messagingSenderId: '671469241941',
    projectId: 'block-sajid',
    authDomain: 'block-sajid.firebaseapp.com',
    storageBucket: 'block-sajid.appspot.com',
    measurementId: 'G-YQEC6B3NSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUcCLhVuvpdWEof63Ifa5b_eAnRGHBpPA',
    appId: '1:671469241941:android:4d77ab76065ae843d3f6dc',
    messagingSenderId: '671469241941',
    projectId: 'block-sajid',
    storageBucket: 'block-sajid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYkBo-ouuRXW-1yGcC9p7TWCzprd3e0gk',
    appId: '1:671469241941:ios:2b976db7a846c1eed3f6dc',
    messagingSenderId: '671469241941',
    projectId: 'block-sajid',
    storageBucket: 'block-sajid.appspot.com',
    iosBundleId: 'com.example.locIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYkBo-ouuRXW-1yGcC9p7TWCzprd3e0gk',
    appId: '1:671469241941:ios:160bd955fad2be4dd3f6dc',
    messagingSenderId: '671469241941',
    projectId: 'block-sajid',
    storageBucket: 'block-sajid.appspot.com',
    iosBundleId: 'com.example.locIt.RunnerTests',
  );
}
